services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    env_file:
      - .env

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env
